addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.3.7")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.5.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "2.0.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.11")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "2.5")
